### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by carpii** [bodnaristvan/JSHint.tmbundle#1]
After installing the bundle, attempting to lint any file in my project, just opens a new window with 
'JSHint: line 23: node: command not found'

Using TM 2.0-alpha.9515, node v0.10.17

Feels like its something obvious, but I cant quite figure it out. Any help please?

**Comment by carpii** [comment]
I fixed this in the end, although probably not the best solution. It turns out that scripts on my system beginning with "#!/bin/env node" are unable to locate node, despite it being in my PATH (/usr/local/bin)

I couldn't find a better solution, but symlinking /bin/node -> /usr/local/bin/node worked

I'd love to know what the real problem is though. 
Closing ticket anyway as its not a JSHint issue

**Comment by ebow** [comment]
I had the same issue. It'll be because node is not in the execution path that the bundle runs in.

I solved it by finding where node was installed on my system (may depend on how you installed it). Then edited the JSHint Bundle in TextMate's Bundle Editor.
![screen shot 2014-03-07 at 11 40 16 am](https://f.cloud.github.com/assets/12644/2352729/297b92f2-a591-11e3-9432-7bb1190585c6.png)

 Right at the bottom of the 2 Menu Action scripts ("JSHint" and "JSHint and save") you'll see a command starting with "node index.js ..."

I just added the exact path to my node binary in there.
![screen shot 2014-03-07 at 11 40 49 am](https://f.cloud.github.com/assets/12644/2352732/2e7107b0-a591-11e3-88b9-f997e4995963.png)

/usr/local/bin/node

Not the best solution ... but works for now ;-)

**Comment by ebow** [comment]
eep ... I keep forgetting taking a screenshot on a retina screen makes them HUGE!

**Comment by ebow** [comment]
oops again ... only just noticed you'd responded to your own issue ;-)

**Comment by carpii** [comment]
Just got your email notification. Thanks for the help!
I'll switch to using your solution as its more likely to survive a backup->reinstall :)

**Comment by bodnaristvan** [comment]
I ran into the same issue today, turns out that TextMate2 has its own `$PATH` setup that contains `/usr/local/bin`, but for some reason it's not enabled -- check out Preferences / Variables, the checkbox right next to it is unchecked.
After this env var was enabled, JSHint plugin started working immediately, without changing the bundle!

**Comment by NickStefan** [comment]
Thanks for the tip on enabling the PATH variable. easy fix!
